sonar.projectKey=bc-devops
sonar.projectName=bc-devops
sonar.projectVersion=1.0

sonar.sources=ansible/playbooks,docker,harbor/harbor,monitoring,scripts,.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.git/**,**/harbor/**,**/monitoring/provisioning/**,**/ansible/secrets/**

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
